package com.example.ui

import android.app.Application
import android.graphics.Bitmap
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.viewModelScope
import com.example.data.AppDatabase
import com.example.data.Payment
import com.example.data.Profile
import com.example.utils.QrCodeGenerator
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.stateIn
import kotlinx.coroutines.launch

class PosViewModel(application: Application) : AndroidViewModel(application) {
    private val database = AppDatabase.getDatabase(application)
    private val dao = database.posDao()

    // Observe Profile and Transaction History loaded from room
    val profile: StateFlow<Profile?> = dao.getProfileFlow()
        .stateIn(viewModelScope, SharingStarted.WhileSubscribed(5000), null)

    val payments: StateFlow<List<Payment>> = dao.getAllPayments()
        .stateIn(viewModelScope, SharingStarted.WhileSubscribed(5000), emptyList())

    // UI Interactive States
    var amountText by mutableStateOf("0")
        private set

    var selectedBank by mutableStateOf<Bank?>(null)
        private set

    var isSelectingBank by mutableStateOf(false)

    var isQrGenerated by mutableStateOf(false)
        private set

    var qrBitmap by mutableStateOf<Bitmap?>(null)
        private set

    var qrCodeText by mutableStateOf("")
        private set

    var isPrintingReceipt by mutableStateOf(false)
        private set

    var showHistoryScreen by mutableStateOf(false)

    var lastPrintedPayment by mutableStateOf<Payment?>(null)
        private set

    fun setQuickAmount(cents: String) {
        if (isQrGenerated || isPrintingReceipt) return
        amountText = cents
    }

    // Digit POS tactile key functions
    fun onDigitPressed(digit: Char) {
        if (isQrGenerated || isPrintingReceipt) return
        if (amountText.length >= 8) return // Limit to avoid screen overflow
        
        if (amountText == "0") {
            if (digit != '0') {
                amountText = digit.toString()
            }
        } else {
            amountText += digit
        }
    }

    fun onDoubleZeroPressed() {
        if (isQrGenerated || isPrintingReceipt) return
        if (amountText == "0") return
        if (amountText.length >= 7) return
        amountText += "00"
    }

    fun onClearPressed() {
        if (isQrGenerated || isPrintingReceipt) return
        if (amountText.length > 1) {
            amountText = amountText.dropLast(1)
        } else {
            amountText = "0"
        }
    }

    fun onCancelPressed() {
        if (isPrintingReceipt) return
        if (isQrGenerated) {
            isQrGenerated = false
            qrBitmap = null
            qrCodeText = ""
        } else {
            amountText = "0"
            selectedBank = null
        }
    }

    fun onBankSelected(bank: Bank) {
        selectedBank = bank
        isSelectingBank = false
    }

    fun onEnterPressed() {
        if (isPrintingReceipt) return
        
        if (isQrGenerated) {
            // Confirming from QR code page triggers slip simulation print and registers transaction
            triggerReceiptPrint()
            return
        }

        val cents = amountText.toDoubleOrNull() ?: 0.0
        if (cents <= 0.0) return

        if (selectedBank == null) {
            // Prompt the user to select bank first
            isSelectingBank = true
            return
        }

        val activeProfile = profile.value ?: return
        val amountLira = cents / 100.0
        val bank = selectedBank!!
        
        // Generate actual FAST compatible standard Turkish QR payload
        val qrPayload = generateFASTQRString(activeProfile.iban, activeProfile.ownerName, amountLira, bank.tcmbCode)
        qrCodeText = qrPayload
        
        // Create QR code bitmap
        qrBitmap = QrCodeGenerator.generateQrCode(qrPayload, 512)
        isQrGenerated = true
    }

    fun selectBankDirectly() {
        if (profile.value == null) return
        isSelectingBank = true
    }

    fun triggerReceiptPrint() {
        if (isPrintingReceipt) return
        val cents = amountText.toDoubleOrNull() ?: 0.0
        val amountLira = cents / 100.0
        val bankName = selectedBank?.name ?: "Bilinmeyen Banka"
        
        val newPayment = Payment(
            amount = amountLira,
            bankName = bankName,
            explanation = "Bayram Harçlığı"
        )
        
        isPrintingReceipt = true
        lastPrintedPayment = newPayment
        
        viewModelScope.launch {
            // Simulate sound feedback or printer timing
            kotlinx.coroutines.delay(2200)
            
            // Record to Database
            dao.insertPayment(newPayment)
            
            isPrintingReceipt = false
            isQrGenerated = false
            qrBitmap = null
            amountText = "0"
            selectedBank = null
        }
    }

    fun saveProfile(ownerName: String, iban: String) {
        viewModelScope.launch {
            val sanitized = iban.replace(" ", "").uppercase()
            val formattedIban = if (sanitized.startsWith("TR")) sanitized else "TR$sanitized"
            dao.insertProfile(Profile(id = 1, ownerName = ownerName.trim(), iban = formattedIban))
        }
    }

    fun deleteProfile() {
        viewModelScope.launch {
            dao.insertProfile(Profile(id = 1, ownerName = "", iban = ""))
        }
    }

    fun clearHistory() {
        viewModelScope.launch {
            dao.clearPayments()
        }
    }

    fun getFormattedAmount(): String {
        val cents = amountText.toDoubleOrNull() ?: 0.0
        val liras = cents / 100.0
        return String.format(java.util.Locale("tr", "TR"), "%,.2f ₺", liras)
    }

    private fun generateFASTQRString(iban: String, name: String, amount: Double, tcmbBankCode: String): String {
        val cleanIban = iban.replace(" ", "").uppercase()
        // Replace Turkish-specific letters to preserve standard scanner character sets
        val cleanName = name.uppercase()
            .replace('Ç', 'C')
            .replace('Ğ', 'G')
            .replace('I', 'I')
            .replace('İ', 'I')
            .replace('Ö', 'O')
            .replace('Ş', 'S')
            .replace('Ü', 'U')
        val amountFormatted = String.format(java.util.Locale.US, "%.2f", amount)
        
        // Return Turkish Central Bank FAST specification TRQR structure
        return "000201010212" +
                "26" + String.format("%02d", 22 + cleanIban.length + cleanName.length) + 
                "0010TR.FAST.QR" +
                "01" + String.format("%02d", cleanIban.length) + cleanIban +
                "02" + String.format("%02d", cleanName.length) + cleanName +
                "54" + String.format("%02d", amountFormatted.length) + amountFormatted +
                "5303949"
    }
}
